const CONSO_PAR_KM        = 0.53
const PRIX_LITRE_DEFAUT   = Number(process.env.PRIX_LITRE_DEFAUT) || 680
const SEUIL_MAINTENANCE_KM = 5000

module.exports = { CONSO_PAR_KM, PRIX_LITRE_DEFAUT, SEUIL_MAINTENANCE_KM }
